const MIN_SPLASH_MS = 1180;
let bootObserver = null;
let lastProgress = 8;

function launchEl(id) { return document.getElementById(id); }
function sleep(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }
function timeout(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }

function suppressAchievementBurst() {
  if (!window.__TCG_BOOT_PHASE__) return;
  const burst = document.getElementById('v163UnlockBurst');
  if (!burst) return;
  burst.classList.remove('show');
  burst.style.setProperty('display', 'none', 'important');
  burst.dataset.bootSuppressed = '1';
}

export function beginLaunch() {
  window.__TCG_BOOT_PHASE__ = true;
  suppressAchievementBurst();
  if (!bootObserver) {
    bootObserver = new MutationObserver(() => suppressAchievementBurst());
    bootObserver.observe(document.documentElement, { subtree: true, childList: true, attributes: true, attributeFilter: ['class'] });
  }
  return document.getElementById('tcgLaunch');
}

export function setLaunchStage(label, progress, hint) {
  const root = launchEl('tcgLaunch');
  if (!root) return;
  lastProgress = Math.max(lastProgress, Math.min(100, Number(progress) || 0));
  const stage = launchEl('tcgLaunchStage');
  const pct = launchEl('tcgLaunchPct');
  const bar = launchEl('tcgLaunchBar');
  const hintEl = launchEl('tcgLaunchHint');
  if (stage) stage.textContent = String(label || 'LOADING').toUpperCase();
  if (pct) pct.textContent = `${Math.round(lastProgress)}%`;
  if (bar) bar.style.width = `${lastProgress}%`;
  if (hint && hintEl) hintEl.textContent = hint;
}

function imageReady(img) {
  if (!img?.src) return Promise.resolve();
  if (img.complete && img.naturalWidth) return img.decode?.().catch(() => {}) || Promise.resolve();
  return new Promise(resolve => {
    const done = () => resolve();
    img.addEventListener('load', done, { once: true });
    img.addEventListener('error', done, { once: true });
  });
}

export async function prewarmFirstFrame() {
  const mustExist = ['pack', 'v114PackMode', 'gameClockV170'];
  const started = performance.now();
  while (performance.now() - started < 1800) {
    if (mustExist.every(id => document.getElementById(id)) && document.querySelector('.nav')) break;
    await sleep(35);
  }

  const fontPromise = document.fonts?.ready || Promise.resolve();
  const images = [
    document.getElementById('packArt'),
    ...Array.from(document.querySelectorAll('#sets .set.selected img,#sets .set img')).slice(0, 5)
  ].filter(Boolean);
  await Promise.race([
    Promise.allSettled([fontPromise, ...images.map(imageReady)]),
    timeout(1400)
  ]);
  await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)));
}

export async function finishLaunch() {
  setLaunchStage('COLLECTION READY', 100, 'Welcome back, collector.');
  const elapsed = performance.now() - Number(window.__TCG_BOOT_STARTED__ || performance.now());
  if (elapsed < MIN_SPLASH_MS) await sleep(MIN_SPLASH_MS - elapsed);

  // Any unlock generated by save migration/reconciliation during boot is data
  // reconciliation, not a new player event. Clear only the visual burst.
  const burst = document.getElementById('v163UnlockBurst');
  if (burst) {
    burst.classList.remove('show');
    burst.style.removeProperty('display');
    burst.textContent = '';
    delete burst.dataset.bootSuppressed;
  }

  document.documentElement.classList.remove('modern-booting');
  await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)));
  const root = launchEl('tcgLaunch');
  root?.classList.add('v2541Leaving');
  await sleep(440);
  root?.remove();
  window.__TCG_BOOT_PHASE__ = false;
  bootObserver?.disconnect();
  bootObserver = null;
}

export function failLaunch(stage, error) {
  const root = launchEl('tcgLaunch');
  root?.classList.add('failed');
  const message = String(error?.message || error || 'Unknown startup error');
  setLaunchStage('STARTUP PROBLEM', Math.max(15, lastProgress), `${stage}: ${message} • tap to retry`);
  if (root) root.onclick = () => location.reload();
  return message;
}
