-- V255 Multiplayer Arena
-- Applied live to ddeuwrnfmdgvizkrjhii on 2026-10-03.

alter table public.mp_battle_rooms
  add column if not exists host_ready boolean not null default false,
  add column if not exists guest_ready boolean not null default false,
  add column if not exists ready_at timestamptz,
  add column if not exists intro_started_at timestamptz;

alter table public.mp_profiles
  add column if not exists avatar_data text,
  add column if not exists banner_title text not null default 'Collector',
  add column if not exists banner_style text not null default 'aurora',
  add column if not exists banner_badges jsonb not null default '[]'::jsonb,
  add column if not exists banner_show_record boolean not null default true,
  add column if not exists ranked_rp numeric not null default 0,
  add column if not exists ranked_wins integer not null default 0,
  add column if not exists ranked_losses integer not null default 0,
  add column if not exists ranked_ties integer not null default 0,
  add column if not exists ranked_streak integer not null default 0,
  add column if not exists ranked_season_high numeric not null default 0,
  add column if not exists last_seen timestamptz;

create table if not exists public.mp_global_chat (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  message text not null,
  created_at timestamptz not null default now()
);
create index if not exists mp_global_chat_created_idx on public.mp_global_chat(created_at desc);
create index if not exists mp_global_chat_user_created_idx on public.mp_global_chat(user_id,created_at desc);
alter table public.mp_global_chat enable row level security;
drop policy if exists "mp global chat readable" on public.mp_global_chat;
create policy "mp global chat readable" on public.mp_global_chat for select to authenticated using (true);

create or replace function public.mp_set_public_profile(
  p_avatar_data text default null,
  p_banner_title text default 'Collector',
  p_banner_style text default 'aurora',
  p_banner_badges jsonb default '[]'::jsonb,
  p_banner_show_record boolean default true
) returns public.mp_profiles
language plpgsql security definer set search_path=''
as $$
declare
  v_uid uuid := auth.uid(); v_row public.mp_profiles; v_title text; v_style text; v_badges jsonb;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
  perform public.mp_ensure_profile(null);
  if p_avatar_data is not null and char_length(p_avatar_data) > 180000 then raise exception 'AVATAR_TOO_LARGE'; end if;
  v_title := left(coalesce(nullif(trim(p_banner_title),''),'Collector'),28);
  v_style := lower(coalesce(nullif(trim(p_banner_style),''),'aurora'));
  if v_style not in ('aurora','obsidian','gold','neon','crystal','ember') then v_style := 'aurora'; end if;
  v_badges := coalesce(p_banner_badges,'[]'::jsonb);
  if jsonb_typeof(v_badges) <> 'array' then v_badges := '[]'::jsonb; end if;
  if jsonb_array_length(v_badges) > 3 then
    select coalesce(jsonb_agg(value),'[]'::jsonb) into v_badges
    from (select value from jsonb_array_elements(v_badges) with ordinality x(value,n) where n<=3) s;
  end if;
  update public.mp_profiles
  set avatar_data=nullif(p_avatar_data,''), banner_title=v_title, banner_style=v_style,
      banner_badges=v_badges, banner_show_record=coalesce(p_banner_show_record,true),
      last_seen=clock_timestamp(), updated_at=clock_timestamp()
  where user_id=v_uid returning * into v_row;
  return v_row;
end; $$;

create or replace function public.mp_send_global_chat(p_message text)
returns public.mp_global_chat
language plpgsql security definer set search_path=''
as $$
declare v_uid uuid:=auth.uid(); v_msg text; v_row public.mp_global_chat;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
  perform public.mp_ensure_profile(null);
  v_msg := trim(regexp_replace(coalesce(p_message,''), E'[\n\r\t]+', ' ', 'g'));
  if char_length(v_msg)<1 then raise exception 'MESSAGE_REQUIRED'; end if;
  if char_length(v_msg)>180 then raise exception 'MESSAGE_TOO_LONG'; end if;
  if exists(select 1 from public.mp_global_chat where user_id=v_uid and created_at>clock_timestamp()-interval '2 seconds') then raise exception 'CHAT_RATE_LIMIT'; end if;
  if (select count(*) from public.mp_global_chat where user_id=v_uid and created_at>clock_timestamp()-interval '1 minute')>=20 then raise exception 'CHAT_RATE_LIMIT'; end if;
  insert into public.mp_global_chat(user_id,message) values(v_uid,v_msg) returning * into v_row;
  update public.mp_profiles set last_seen=clock_timestamp(),updated_at=clock_timestamp() where user_id=v_uid;
  return v_row;
end; $$;

create or replace function public.mp_set_battle_ready(p_room_id uuid,p_ready boolean)
returns public.mp_battle_rooms
language plpgsql security definer set search_path=''
as $$
declare v_uid uuid:=auth.uid(); v_room public.mp_battle_rooms;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
  select * into v_room from public.mp_battle_rooms where id=p_room_id for update;
  if not found or (v_room.host_id<>v_uid and v_room.guest_id<>v_uid) then raise exception 'ROOM_NOT_FOUND'; end if;
  if v_room.room_type<>'matchmaking' then return v_room; end if;
  if v_room.status in ('completed','cancelled') then return v_room; end if;
  if v_room.guest_id is null then raise exception 'WAITING_FOR_OPPONENT'; end if;
  if v_room.host_progress>0 or v_room.guest_progress>0 or v_room.host_score is not null or v_room.guest_score is not null then raise exception 'BATTLE_ALREADY_STARTED'; end if;
  if v_room.host_id=v_uid then
    update public.mp_battle_rooms set host_ready=coalesce(p_ready,false),updated_at=clock_timestamp() where id=p_room_id;
  else
    update public.mp_battle_rooms set guest_ready=coalesce(p_ready,false),updated_at=clock_timestamp() where id=p_room_id;
  end if;
  select * into v_room from public.mp_battle_rooms where id=p_room_id for update;
  if v_room.host_ready and v_room.guest_ready then
    update public.mp_battle_rooms set status='ready',ready_at=coalesce(ready_at,clock_timestamp()),intro_started_at=coalesce(intro_started_at,clock_timestamp()),updated_at=clock_timestamp() where id=p_room_id returning * into v_room;
  else
    update public.mp_battle_rooms set status='waiting',ready_at=null,intro_started_at=null,updated_at=clock_timestamp() where id=p_room_id returning * into v_room;
  end if;
  return v_room;
end; $$;

create or replace function public.mp_find_battle_match(p_set_id text default 'sv04.5')
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v_uid uuid:=auth.uid(); v_row public.mp_battle_rooms; v_code text;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
  perform public.mp_ensure_profile(null);
  update public.mp_battle_rooms set status='cancelled',updated_at=clock_timestamp()
    where room_type='matchmaking' and status='waiting' and guest_id is null and created_at<clock_timestamp()-interval '3 minutes';
  update public.mp_battle_rooms set status='cancelled',updated_at=clock_timestamp()
    where room_type='matchmaking' and status='waiting' and guest_id is not null and not(host_ready and guest_ready) and updated_at<clock_timestamp()-interval '5 minutes';
  select * into v_row from public.mp_battle_rooms
    where room_type='matchmaking' and status in ('waiting','ready','playing') and (host_id=v_uid or guest_id=v_uid)
    order by created_at desc limit 1 for update;
  if found then return jsonb_build_object('matched',v_row.guest_id is not null,'room',to_jsonb(v_row)); end if;
  select * into v_row from public.mp_battle_rooms
    where room_type='matchmaking' and status='waiting' and guest_id is null and host_id<>v_uid and created_at>=clock_timestamp()-interval '3 minutes'
    order by created_at asc limit 1 for update skip locked;
  if found then
    update public.mp_battle_rooms set guest_id=v_uid,status='waiting',host_ready=false,guest_ready=false,ready_at=null,intro_started_at=null,updated_at=clock_timestamp()
    where id=v_row.id returning * into v_row;
    return jsonb_build_object('matched',true,'room',to_jsonb(v_row));
  end if;
  loop
    v_code:=upper(substr(md5(gen_random_uuid()::text),1,8));
    begin
      insert into public.mp_battle_rooms(room_code,host_id,set_id,pack_count,room_type,host_ready,guest_ready)
      values(v_code,v_uid,coalesce(nullif(p_set_id,''),'sv04.5'),1,'matchmaking',false,false) returning * into v_row;
      exit;
    exception when unique_violation then null;
    end;
  end loop;
  return jsonb_build_object('matched',false,'room',to_jsonb(v_row));
end; $$;

create or replace function public.mp_update_battle_progress(p_room_id uuid,p_progress integer)
returns public.mp_battle_rooms language plpgsql security definer set search_path=''
as $$
declare v_uid uuid:=auth.uid(); v_room public.mp_battle_rooms; v_progress integer:=greatest(0,least(10,coalesce(p_progress,0)));
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
  select * into v_room from public.mp_battle_rooms where id=p_room_id for update;
  if not found or (v_room.host_id<>v_uid and v_room.guest_id<>v_uid) then raise exception 'ROOM_NOT_FOUND'; end if;
  if v_room.status in ('completed','cancelled') then return v_room; end if;
  if v_room.room_type='matchmaking' and not(v_room.host_ready and v_room.guest_ready) then raise exception 'PLAYERS_NOT_READY'; end if;
  if v_room.host_id=v_uid then
    update public.mp_battle_rooms set host_progress=greatest(host_progress,v_progress),host_started_at=coalesce(host_started_at,clock_timestamp()),status=case when guest_id is null then status else 'playing' end,updated_at=clock_timestamp() where id=p_room_id returning * into v_room;
  else
    update public.mp_battle_rooms set guest_progress=greatest(guest_progress,v_progress),guest_started_at=coalesce(guest_started_at,clock_timestamp()),status='playing',updated_at=clock_timestamp() where id=p_room_id returning * into v_room;
  end if;
  return v_room;
end; $$;

create or replace function public.mp_submit_battle_result(p_room_id uuid,p_score numeric,p_result jsonb)
returns public.mp_battle_rooms language plpgsql security definer set search_path=''
as $$
declare v_uid uuid:=auth.uid(); v_row public.mp_battle_rooms;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_score<0 or p_score>10000000 then raise exception 'INVALID_SCORE'; end if;
  select * into v_row from public.mp_battle_rooms where id=p_room_id for update;
  if not found or (v_row.host_id<>v_uid and v_row.guest_id<>v_uid) then raise exception 'ROOM_NOT_FOUND'; end if;
  if v_row.guest_id is null then raise exception 'WAITING_FOR_FRIEND'; end if;
  if v_row.room_type='matchmaking' and not(v_row.host_ready and v_row.guest_ready) then raise exception 'PLAYERS_NOT_READY'; end if;
  if v_row.status='completed' then return v_row; end if;
  if v_row.host_id=v_uid then
    if v_row.host_score is not null then raise exception 'RESULT_ALREADY_SUBMITTED'; end if;
    update public.mp_battle_rooms set host_score=round(p_score,2),host_result=p_result,status='playing',updated_at=now() where id=p_room_id;
  else
    if v_row.guest_score is not null then raise exception 'RESULT_ALREADY_SUBMITTED'; end if;
    update public.mp_battle_rooms set guest_score=round(p_score,2),guest_result=p_result,status='playing',updated_at=now() where id=p_room_id;
  end if;
  select * into v_row from public.mp_battle_rooms where id=p_room_id for update;
  if v_row.host_score is not null and v_row.guest_score is not null then
    update public.mp_battle_rooms set status='completed',winner_id=case when host_score>guest_score then host_id when guest_score>host_score then guest_id else null end,completed_at=clock_timestamp(),updated_at=clock_timestamp() where id=p_room_id returning * into v_row;
  end if;
  return v_row;
end; $$;

create or replace function public.mp_recalculate_profile_rank(p_uid uuid)
returns void language plpgsql security definer set search_path=''
as $$
declare r record; v_rp numeric:=0; v_w integer:=0; v_l integer:=0; v_t integer:=0; v_streak integer:=0; v_high numeric:=0; v_delta numeric; v_my numeric; v_opp numeric; v_my_set text; v_opp_set text;
begin
  if p_uid is null then return; end if;
  for r in select * from public.mp_battle_rooms where room_type='matchmaking' and status='completed' and (host_id=p_uid or guest_id=p_uid) order by coalesce(completed_at,updated_at,created_at),created_at loop
    if r.host_id=p_uid then
      v_my:=coalesce(r.host_score,0); v_opp:=coalesce(r.guest_score,0); v_my_set:=coalesce(r.host_result->>'setId',''); v_opp_set:=coalesce(r.guest_result->>'setId','');
    else
      v_my:=coalesce(r.guest_score,0); v_opp:=coalesce(r.host_score,0); v_my_set:=coalesce(r.guest_result->>'setId',''); v_opp_set:=coalesce(r.host_result->>'setId','');
    end if;
    if r.winner_id is null then v_t:=v_t+1; v_streak:=0; v_delta:=8;
    elsif r.winner_id=p_uid then
      v_w:=v_w+1; v_streak:=v_streak+1; v_delta:=30+least(12,greatest(0,v_streak-1)*3);
      if v_my_set<>'' and v_opp_set<>'' and v_my_set<>v_opp_set then v_delta:=v_delta+4; end if;
      if abs(v_my-v_opp)<350 then v_delta:=v_delta+3; end if;
    else
      v_l:=v_l+1; v_streak:=0; v_delta:=case when v_rp<250 then -6 when v_rp<700 then -9 else -12 end;
      if abs(v_my-v_opp)<350 then v_delta:=v_delta+2; end if;
    end if;
    v_rp:=greatest(0,v_rp+v_delta); v_high:=greatest(v_high,v_rp);
  end loop;
  update public.mp_profiles set ranked_rp=v_rp,ranked_wins=v_w,ranked_losses=v_l,ranked_ties=v_t,ranked_streak=v_streak,ranked_season_high=v_high,updated_at=clock_timestamp() where user_id=p_uid;
end; $$;

create or replace function public.mp_ranked_profile_trigger()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  if new.room_type='matchmaking' and new.status='completed' and old.status is distinct from 'completed' then
    perform public.mp_recalculate_profile_rank(new.host_id);
    perform public.mp_recalculate_profile_rank(new.guest_id);
  end if;
  return new;
end; $$;

drop trigger if exists mp_ranked_profile_after_battle on public.mp_battle_rooms;
create trigger mp_ranked_profile_after_battle after update of status on public.mp_battle_rooms for each row execute function public.mp_ranked_profile_trigger();

do $$ declare r record; begin for r in select user_id from public.mp_profiles loop perform public.mp_recalculate_profile_rank(r.user_id); end loop; end $$;

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='mp_global_chat') then
    alter publication supabase_realtime add table public.mp_global_chat;
  end if;
end $$;

grant execute on function public.mp_set_public_profile(text,text,text,jsonb,boolean) to authenticated;
grant execute on function public.mp_send_global_chat(text) to authenticated;
grant execute on function public.mp_set_battle_ready(uuid,boolean) to authenticated;
